import Head from 'next/head'
import { useState } from 'react'
import Body from '../components/Body'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function Home() {
  const [address, setAddress] = useState('')
  const getAddy = async (addy) => {
    setAddress(addy)
  }

  return (
    <div className="h-screen">
      <div className="text-gray-200 bg-gradient-to-b from-black via-neutral-900 to-red-900">
        <div className="p-3 sm:px-5">
          <Head>
            <title>Uchiha Token</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <Header addy={getAddy} newAddy={address} />
        </div>
        <Body addy={address} newAddy={getAddy} />
        <Footer />
      </div>
    </div>
  )
}
